version: '3.9'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: spring-config/Dockerfile
    container_name: spring-boot-app
    ports:
      - "${LOCAL_PORT}:${SERVER_PORT}"
    depends_on:
      - redis
      - mariadb
    networks:
      - springapi-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - springapi-net

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - springapi-net  
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      
volumes:
  mariadb_data:

networks:
  springapi-net: